import type { GalleryProject } from "./types";

export const GALLERY_PROJECTS: GalleryProject[] = [
  {
    id: "judy-b",
    title: "Judy.B",
    client: "Judy.B",
    image: "/images/projects/judy-b.jpg",
    category: "saas",
    description: "Refactoring a legacy dashboard to reduce user error by 40%.",
    details: "Judy.B needed a professional brand that conveyed expertise while remaining approachable. We developed a comprehensive visual identity including logo design, color palette, typography system, and marketing materials. The result is a cohesive brand that positions them as trusted partners for small businesses.",
    metric: "76% Faster Workflow",
  },
  {
    id: "fazenda-machado",
    title: "Fazenda Machado",
    client: "Fazenda Machado",
    image: "/images/projects/fazenda-machado.jpg",
    category: "enterprise",
    description: "Streamlining supply chain operations across 12 distribution centers.",
    details: "This family-owned farm needed to modernize their brand while honoring their heritage. We created a visual identity that bridges tradition and innovation, emphasizing their commitment to sustainable practices and quality products.",
    metric: "3x Revenue Lift",
  },
  {
    id: "maven-advisory",
    title: "Maven Advisory",
    client: "Maven Advisory",
    image: "/images/projects/maven-advisory.jpg",
    category: "fintech",
    description: "Redesigning compliance workflows to meet regulatory requirements without sacrificing speed.",
    details: "Maven Advisory required a sophisticated brand that would resonate with C-level executives. We developed a premium visual identity with a focus on trust, expertise, and strategic thinking.",
    metric: "Acquired",
  },
  {
    id: "byting-chipmunk",
    title: "Byting Chipmunk",
    client: "Byting Chipmunk",
    image: "/images/projects/byting-chipmunk.jpg",
    category: "identity systems",
    description: "Building a scalable design system to support 50+ product teams.",
    details: "This tech startup wanted to stand out in a crowded market. We created a memorable brand with a unique mascot, vibrant color palette, and modern design system that appeals to both technical and non-technical audiences.",
    metric: "Launch",
  },
  {
    id: "anna-burgess-yang",
    title: "Anna Burgess Yang",
    client: "Anna Burgess Yang",
    image: "/images/projects/anna-burgess-yang.jpg",
    category: "saas",
    description: "Optimizing onboarding flows to increase activation rates by 65%.",
    details: "Anna needed a personal brand that reflected her authentic voice and expertise in content strategy. We developed a warm, approachable visual identity with custom typography and a flexible design system for her content.",
    metric: "65% Activation",
  },
  {
    id: "fruition-initiatives",
    title: "Fruition Initiatives",
    client: "Fruition Initiatives",
    image: "/images/projects/fruition-initiatives.jpg",
    category: "enterprise",
    description: "Consolidating fragmented tools into a unified platform for 10K+ users.",
    details: "Fruition Initiatives helps businesses achieve their growth goals. We created a brand that communicates progress, strategy, and results through a dynamic visual identity and compelling messaging.",
    metric: "3x Revenue Lift",
  },
  {
    id: "wordpotential",
    title: "WordPotential",
    client: "WordPotential",
    image: "/images/projects/wordpotential.jpg",
    category: "saas",
    description: "Reducing cognitive load in content workflows through intelligent automation.",
    details: "WordPotential transforms ideas into compelling copy. We designed a brand that emphasizes the power of words through thoughtful typography, clean layouts, and a sophisticated color palette.",
    metric: "76% Faster Workflow",
  },
  {
    id: "justice-is-now",
    title: "Justice Is Now",
    client: "Justice Is Now",
    image: "/images/projects/justice-is-now.jpg",
    category: "identity systems",
    description: "Creating accessible interfaces that meet WCAG AAA standards without compromise.",
    details: "This advocacy organization needed a brand that would inspire action and communicate urgency. We created a powerful visual identity with strong typography, impactful imagery, and a bold color scheme.",
    metric: "Launch",
  },
  {
    id: "canopie",
    title: "Canopie",
    client: "Canopie",
    image: "/images/projects/canopie.jpg",
    category: "fintech",
    description: "Simplifying complex financial data visualization for real-time decision making.",
    details: "Canopie champions environmental sustainability. We developed a brand that reflects their values through natural colors, organic shapes, and imagery that connects people with nature.",
    metric: "Acquired",
  },
  {
    id: "gira-sonhos",
    title: "Gira Sonhos",
    client: "Gira Sonhos",
    image: "/images/projects/gira-sonhos.jpg",
    category: "saas",
    description: "Rebuilding core infrastructure to support 10x scale without performance degradation.",
    details: "Gira Sonhos (Dream Spinner) needed a brand as imaginative as their work. We created a whimsical yet professional identity with playful elements and a vibrant color palette.",
    metric: "Launch",
  },
  {
    id: "view-from-32",
    title: "View From 32",
    client: "View From 32",
    image: "/images/projects/view-from-32.jpg",
    category: "enterprise",
    description: "Architecting multi-tenant systems with enterprise-grade security and isolation.",
    details: "This personal platform needed a clean, distraction-free brand that lets the content shine. We designed a minimalist identity with elegant typography and subtle visual elements.",
    metric: "3x Revenue Lift",
  },
  {
    id: "eggshells",
    title: "Eggshells",
    client: "Eggshells",
    image: "/images/projects/eggshells.jpg",
    category: "identity systems",
    description: "Establishing design principles that scale across mobile, web, and embedded systems.",
    details: "Eggshells provides mental health resources with sensitivity and care. We created a gentle, reassuring brand with soft colors, rounded shapes, and inclusive imagery.",
    metric: "76% Faster Workflow",
  },
];
